### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by primalmotion** [eliaskg/EKShakeAnimation#2]
Hi, I would like to use this in Archipel. Can you add the MIT license as header on the .j file?

**Comment by eliaskg** [comment]
Hi,

https://github.com/elii/EKShakeAnimation/compare/5691233dee...109d5a50bb

Have fun!

**Comment by primalmotion** [comment]
## Thanks ;)

Antoine Mercadal

Le 5 nov. 2011  11:04, Elias Klughammer a crit :
